name: Sandbox

on: [push, pull_request, workflow_dispatch]

jobs:
  # Check out the repository
  checkout: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

  # Execute a command on the runner 
  echo:
    runs-on: ubuntu-latest
    steps:
    - name: Run a multi-line script
      run: |
        echo "the script was ran" > status.txt
        cat status.txt
    - name: Echo something 
      run: echo "time to wrap up"
