name: Sandbox

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository
    - uses: actions/checkout@v3

    # Execute a command on the runner 
    - name: Run a multi-line script
      run: |
        echo "running the script" > status.txt
        cat status.txt

